### ISSUE TITLE
Reconnect code and change URL not working

### ISSUE THREAD

**Issue by freeyland** [clappr/clappr#1659]
From the documentation I found it is possible to keep retrying to connect untill the livestream (HLS) is back online. This works very good. However when trying to change the url via jaquery on click event, it tries once to play the new sream url and then it keeps trying to play the previous url

**Clappr Version**: 0.2.25
CDN

```javascript
var player = new Clappr.Player({
  // source: 'http://clappr.io/highline.mp4',
  source: url,
  disableErrorScreen: true, // Disable the internal error screen plugin
  height: '100%',
  width: '100%',
  events: {
    onError: function(e) {
      //r--;
      var s = player.options.source;

      // Replace previous line by the following line to simulate successful recovery
      // var s = (r > 2) ? player.options.source : 'http://clappr.io/highline.mp4';
      var t = 10;
      var retry = function() {
        if (t === 0) {
          var o = player.options;
          o.source = s;
          player.configure(o);
          return;
        }
        Clappr.$('#retryCounter').text(t);
        t--;
        setTimeout(retry, 1000);
      };

      player.configure({
        autoPlay: true,
        source: 'playback.error',
        playbackNotSupportedMessage: ' Retrying in <span id="retryCounter"></span> seconds ...'
   
      });
        retry();
    }
  }
});

player.attachTo(playerElement);

$(document).ready(function() {

      $(".triggercam").click(function() {
        //player.load('http://192.168.101.15:8080/hls/tria_cam4.m3u8');
        var url = 'http://192.168.101.15:8080/hls/tria_cam4.m3u8';
        var o = player.options;
        o.source = url;
        player.configure(o);
      
        //player.play();
      });
  });
```

**Comment by towerz** [comment]
Fixed code formatting in the previous comment.

**Comment by towerz** [comment]
@freeyland could not reproduce the issue running your code on http://clappr.io/demo (using Clappr 0.2.96). Apparently, it has already been fixed, since you had the issue with a much older version (0.2.25).

I'll close the issue for now, but if you have the same issue with the latest Clappr version, please reopen.

**Comment by freeyland** [comment]
https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js
Hi, ther version used is from jsdelivr: 0.2.96, so it is still an issue

**Comment by towerz** [comment]
Hi @freeyland, I'll reopen it, but can you confirm what's happening and how to reproduce? I ran the following code on http://clappr.io/demo (there are some slight changes from your base code to change the width/height of the player and reduce the time to test):

```javascript
var playerElement = document.getElementById("player-wrapper");

var url = 'http://192.168.101.15:8080/hls/tria_cam4.m3u8';
var r = 3;

var player = new Clappr.Player({
  // source: 'http://clappr.io/highline.mp4',
  source: url,
  disableErrorScreen: true, // Disable the internal error screen plugin
  height: 360,
  width: 640,
  events: {
    onError: function(e) {
      r--;
      var s = (r > 1) ? player.options.source : 'http://clappr.io/highline.mp4';
      var t = 5;
      var retry = function() {
        if (t === 0) {
          var o = player.options;
          o.source = s;
          player.configure(o);
          return;
        }
        Clappr.$('#retryCounter').text(t);
        t--;
        setTimeout(retry, 1000);
      };

      player.configure({
        autoPlay: true,
        source: 'playback.error',
        playbackNotSupportedMessage: ' Retrying in <span id="retryCounter"></span> seconds ...'
   
      });
        retry();
    }
  }
});

player.attachTo(playerElement);
```
This results in having the player attempt to reach `tria_cam4.m3u8` twice, and then fall back into the default `highline.mp4` we use for testing. Notice that there are only two requests to the failing stream, and after changing the source, no more requests are made to the failing resource.

**Comment by freeyland** [comment]
Hi,

I'am sorry but I've tested the code and it is working now. Really strange
I really appreciate your help.
