### ISSUE TITLE
maxBufferLength broken since clappr 0.3.0

### ISSUE THREAD

**Issue by bp2008** [clappr/clappr#1783]
**Browser**: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**OS**: Windows 10 Version 1803

**Clappr Version**: 0.3.0, 0.3.3

**Steps to reproduce**:

* Initialize clappr with argument `maxBufferLength: 30`
e.g.
```js
new Clappr.Player({ maxBufferLength: 30 })
```

* From an HLS source, play a VOD video with duration significantly longer than 30 seconds
* Expected result: buffering should stop when ~30 seconds ahead
* Actual result: buffering continues beyond specified time limit (up to a size limit? around 40 MB it seems?)

Did you try to reproduce this issue at http://cdn.clappr.io/?

Yes:

http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9tbm1lZGlhcy5hcGkudGVsZXF1ZWJlYy50di9tM3U4LzI5ODgwLm0zdTgnLAogIG1heEJ1ZmZlckxlbmd0aDogMzAsCiAgbXV0ZTogdHJ1ZQp9KTsKCnBsYXllci5hdHRhY2hUbyhwbGF5ZXJFbGVtZW50KTs=

---
In Clappr 0.2.100 and older, this works to limit the buffer length.  The same does not work in 0.3.0 and newer:
```
hlsjsConfig:
{
	maxMaxBufferLength: 30
}
```

**Comment by towerz** [comment]
@bp2008 I believe there are 2 different thing here. You mentioned that `maxBufferLength` isn't working with `0.3.0+`, but in previous versions you used `maxMaxBufferLength`. The latter version is actually the correct. There's also the case that the version in which the `maxBufferLength` passed directly in the player option won't work:
```javascript
new Clappr.Player({ maxBufferLength: 30 }) // this is not handled by the hls.js playback
```

If you test hls.js directly, the `maxBufferLength` seems to have a lower priority than `maxBufferSize`, which is by default set to 60 MB. Using `maxMaxBufferLength` as stated in the documentation is the way to go.

The Clappr documentation is somehow ambiguous regarding playback options, which used to be mixed with all other player options. Even on `0.2.x` we changed that to work inside a `playback` group of options:

```javascript
new Clappr.Player({
  playback: {
    hlsjsConfig: {
	maxMaxBufferLength: 30
    }
  }
})
```

There was some code to ensure that the previous behavior, having the `hlsjsConfig` directly in the player options would work, but some unrelated code have broken this backwards-compatible behavior. We'll have it fixed for the next release, but for now, please try to use the way I mentioned before. This way it will work regardless of player version.

We'll also update the documentation accordingly to ensure that this will be more easily understood.

Thanks for reporting this.

**Comment by bp2008** [comment]
To be clear, this is the documentation I was looking at which instructed to use **maxBufferLength** as I did in the reproduction steps:  http://clappr.github.io/classes/Player.html

**Comment by bp2008** [comment]
Thanks.

**Comment by towerz** [comment]
@bp2008 I just released a new version `0.3.4` with the compatibility fix.

You can run this [test](http://clappr.io/demo/#dmFyIHBsYXllckVsZW1lbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGxheWVyLXdyYXBwZXIiKTsKCnZhciBwbGF5ZXIgPSBuZXcgQ2xhcHByLlBsYXllcih7CiAgc291cmNlOiAnaHR0cHM6Ly9tbm1lZGlhcy5hcGkudGVsZXF1ZWJlYy50di9tM3U4LzI5ODgwLm0zdTgnLAogIGhsc2pzQ29uZmlnOiB7IG1heE1heEJ1ZmZlckxlbmd0aDogMzAgfSwKICBtdXRlOiB0cnVlCn0pOwoKcGxheWVyLmF0dGFjaFRvKHBsYXllckVsZW1lbnQpOw==) to confirm it's working.

**Comment by bp2008** [comment]
Ok, that is good for backwards-compatibility.

The `maxBufferLength` option still does not work as described in the documentation, which is what this bug report was all about: http://clappr.github.io/classes/Player.html

**Comment by towerz** [comment]
@bp2008 the `maxBufferLength` option does not work as you think it does. It is just used as the last option of limiting the buffer. 

As it's described in the [hls.js documentation](https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxbufferlength) it's the minimum guaranteed buffer size, not the maximum limit, as you want it to be. The right one is `maxMaxBufferLength` (https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxmaxbufferlength). We also have it documented in the [embed parameters doc](https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#hls-buffer-length).

We need to remove this description from http://clappr.github.io/classes/Player.html, it seems to be **really** outdated. It was only used in the Flash version of the HLS playback, which hasn't been the default for a while.

**Comment by bp2008** [comment]
Aha, now I understand.  This would all have been far less confusing if they had named these settings `minBufferLength` and `maxBufferLength` instead of `maxBufferLength` and `maxMaxBufferLength`.
