### ISSUE TITLE
Can't exit full screen by clicking on fullscreen button

### ISSUE THREAD

**Issue by super23n** [clappr/clappr#1883]
**Browser**: Firefox 69.0.3 (64-bit)

**OS**: Debian 8

**Clappr Version**: https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js

**Steps to reproduce**:
* Start playing a video after page loads, and enter full screen mode.
* And now click on the full screen button to exit full screen.
* It should have exited from full screen, but nothing happens. I exit full screen by pressing ESC key. Also: exiting full screen mode by double clicking on player video does not work as well.

Did you try to reproduce this issue at http://cdn.clappr.io/
Yes, it does not work there either.

I have tested it on Chrome, and there it works.

**Comment by kslimani** [comment]
@super23n thank you for report.

This issue should be already fixed by be20e02e4064867eba5d1ea275249eb6d8b975ca (see also #1878).

It is still in current development branch and therefore should be fixed in next release.

**Comment by super23n** [comment]
I downloaded the zip file of the project and included clappr.min.js (in dist folder) in my project, but the problem still exists.

**Comment by kslimani** [comment]
@super23n i think it is because `npm run build` compile only the non-minified version of the player.

To also compile the minified version locally, try something like `npm run build && npm run release`

**Comment by super23n** [comment]
Yes that helped, the minified file is working now. Thanks, this ticket can be closed.
