### ISSUE TITLE
Bundle JS seems to fail on the new release

### ISSUE THREAD

**Issue by lkkadiri** [clappr/clappr#533]
Our bundleJS task is failing with 0.2.7, and throws the following error

```
/custom-player/node_modules/clappr/src/main.js:5
import Player from './components/player'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Any help with this will be great.

**Comment by lkkadiri** [comment]
@jfairley @dviramontes

**Comment by jfairley** [comment]
because of this https://github.com/clappr/clappr/commit/b309deb795fa0f02cd024f46751385972b1dd3fd

**Comment by towerz** [comment]
@lkkadiri @jfairley it seem like the problem is the entry point for clappr is affecting your build configuration. I'm investigating whether there's a solution for this or if I'll need to revert this change.

What kind of build configuration are you using? I mean, how's clappr included in your build?

**Comment by dviramontes** [comment]
@towerz, 
we are using **browserify**.

**Comment by dviramontes** [comment]
As a temporary fix you can add a browser property to your package.json
(if you are using **browserify**):
```
  "browser": {
    "clappr": "./node_modules/clappr/dist/clappr.min.js"
  }
```

**Comment by lkkadiri** [comment]
Making the change suggested by @dviramontes fixes the build but now the min version of clappr does not seem to find the swf file. I now see this error,

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/js/96f944f0104ee30b8fce6cffd89e13aa.swf?inline=1 
```

**Comment by towerz** [comment]
Just reverted b309deb795fa0f02cd024f46751385972b1dd3fd to avoid breaking browserify usages. I found a way to expose source/assets to webpack without breaking other build systems.

Will release 0.2.8 asap.

**Comment by towerz** [comment]
Done, closing the issue now. If you have further problems, please let me know.

**Comment by lkkadiri** [comment]
@towerz I still get this error, 

```
GET http://localhost:3000/js/96f944f0104ee30b8fce6cffd89e13aa.swf?inline=1  404 (Not Found)
```
Seems like its unable to find the swf file still.

**Comment by towerz** [comment]
@lkkadiri prior to this change, where were clappr getting the swf from?

Since 0.2.4 we changed the default `baseUrl` from `//cdn.clappr.io/${VERSION}` to the base url from where the clappr.min.js script is loaded. In your case, since you are loading the js file from http://localhost:3000/js, this will be set as the player base url, unless you set a `baseUrl` value yourself. If you are hosting your own assets from clappr, I suggest you set the `baseUrl` parameter to point to the corresponding URL from where you are hosting these assets.

For example, if you are saving you js files under `js/` and your assets under `assets/`, just use `baseUrl: "/assets"`.

**Comment by towerz** [comment]
@lkkadiri another thing, if you are using 0.2.8 you won't need to use @dviramontes solution. Just use clappr as you were using before.

**Comment by lkkadiri** [comment]
@towerz thanks for the prompt responses! You Rock buddy!
